### ISSUE TITLE
c_max à la place de c_min

### ISSUE THREAD

**Issue by BreakingBarto** [MoinesCopistes/EDP#1]
https://github.com/MoinesCopistes/EDP/blob/3a9cdcb08fbfeac51fc784b85291e0fe6d7545cf/src/premier_ordre/transport.md?plain=1#L33

Il faut remplacer le 2e  c_min par c_max

**Comment by mxdbck** [comment]
Exact ! C'est corrigé merci, j'ajoute l'extrait du syllabus pour documenter :
Page 17 :
![image](https://github.com/MoinesCopistes/EDP/assets/119764381/36a8c182-b5b2-4d98-8543-37d1ed909a54)
